export const students = [
  {
    id: '1',
    name: 'Наталія Газіна',
    role: 'Team lead',
    img: 'https://avatars.githubusercontent.com/u/106490296?v=4',

    githubLink: 'https://github.com/AuroraPolaire',
    facebookLink: 'https://www.facebook.com/AuroraPolaire',
    linkedinLink: 'https://www.linkedin.com/in/natalia-hazina-vatria/',
    description:
      'The only way to learn a new programming language is by writing programs in it.',
  },
  {
    id: '2',
    name: 'Аліса Кулакова',
    role: 'Scrum-master / Developer',
    img: 'https://avatars.githubusercontent.com/u/110929937?v=4',
    githubLink: 'https://github.com/AliceChpmnk',
    facebookLink: 'https://www.facebook.com/alicakul',
    linkedinLink: 'http://www.linkedin.com/in/alice-kulakova',
    description: 'It was awesome experience with great people!',
  },
  {
    id: '3',
    name: 'Юлія Жукова',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/113676493?v=4',
    githubLink: 'https://github.com/ZhukovaYu',
    facebookLink: 'https://www.facebook.com/',
    linkedinLink:
      'https://www.linkedin.com/in/yuliya-zhukova-%F0%9F%87%BA%F0%9F%87%A6-b248b93/',
    description: 'Stay calm and keep coding.',
  },
  {
    id: '4',
    name: 'Ангеліна Шабріна',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/113515617?v=4',
    githubLink: 'https://github.com/angielinayo',
    facebookLink: 'https://www.facebook.com/angelina.shaposhnikova.1',
    linkedinLink: 'https://www.linkedin.com/in/anhelina-shabrina-256a81117/',
    description: 'Oh those great brainstorming times!',
  },
  {
    id: '5',
    name: 'Юлія Хижук',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/113546468?v=4',
    githubLink: 'https://github.com/YuliaKhyzhuk',
    facebookLink: 'https://www.facebook.com/yulia.khyzhuk',
    linkedinLink: 'https://www.linkedin.com/in/yulia-khyzhuk-497687174',
    description: 'An amazing course for people who actually want to learn.',
  },
  {
    id: '6',
    name: 'Марина Караманова',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/111389457?v=4',
    githubLink: 'https://github.com/Karamanova',
    facebookLink: 'https://www.facebook.com/marina.karamanova',
    linkedinLink: 'https://www.linkedin.com/in/maryna-karamanova-4a77bab1/',
    description: 'Great possibility to test my skills!',
  },
  {
    id: '7',
    name: 'Христина Сайгак',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/113846974?v=4',
    githubLink: 'https://github.com/KhrystynaSaihak',
    facebookLink: 'https://www.facebook.com/khrystynass',
    linkedinLink: 'https://www.linkedin.com/in/',
    description: 'I really enjoyed the course.',
  },
  {
    id: '8',
    name: 'Паша Ключенко',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/88260408?v=4',
    githubLink: 'https://github.com/Kliuchenko',
    facebookLink: 'https://www.facebook.com/kliuchenko',
    linkedinLink: 'https://www.linkedin.com/in/',
    description:
      'Важкувато поєднувати з військовою службою, але курс дуже цікавий :)',
  },
  {
    id: '9',
    name: 'Ольга Радковська',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/103367164?v=4',
    githubLink: 'https://github.com/OlgaRadkovska/',
    facebookLink: 'https://www.facebook.com/radkovskaya.olga',
    linkedinLink: 'https://www.linkedin.com/in/olga-radkovskaya-a31543210/',
    description: 'Отримала зарядку для мозку, про яку мріяла :)',
  },
  {
    id: '10',
    name: 'Віталій Павлюк',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/113640099?v=4',
    githubLink: 'https://github.com/VitaliiPavliuk',
    facebookLink: 'https://www.facebook.com/vitalii.m.pavliuk',
    linkedinLink: 'https://www.linkedin.com/in/pavliuk-vitalii',
    description: 'Firebase is awesome! :)',
  },
  {
    id: '11',
    name: 'Дмитро Сакалюк',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/78900270?v=4',
    githubLink: 'https://github.com/owin66',
    facebookLink: 'https://www.facebook.com/profile.php?id=100005161834760',
    linkedinLink: 'https://www.linkedin.com/in/dmitriy-sakaluk/',
    description: 'Lorem ipsum ipsum lorem!',
  },
];
